### ISSUE TITLE
All unit tests fail when run in Visual Studio

### ISSUE THREAD

**Issue by KyleS22** [IxLahiji/CMPT371Team3#10]
When running unit tests in visual studio, every test fails with the error:
`Test Failed:  System.SecurityException: ECall methods must be packaged into a system module`

**Project Version**: ID2

## Platform Details
**OS**: Windows 10
**Software**: Visual Studio 2015 Community, NUnit 3.0.0

**Comment by EvanSnook** [comment]
run the tests through the Unity editor Instead
