### ISSUE TITLE
Send Message receiver Error

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#100]
This is due to messages from the dashboard buttons sending messages to disabled Copies.  Must fix this.

**Comment by KyleS22** [comment]
This issue may not cause direct disturbance to usability, but does have an underlying memory problem.  We should look into ways of disposing of objects, rather than just disabling them.

**Comment by snovan** [comment]
this issue was fixed now that copies are properly deleted as per Unity's message handling
