### ISSUE TITLE
Environment prefab missing in built executeable

### ISSUE THREAD

**Issue by oitoku** [IxLahiji/CMPT371Team3#107]
The appropriate ID4_demo scene runs as expected from within the Unity editor, but when the built executable is run, the Environment prefab, containing the dark room for the scene, is missing. All other functionality is preserved, including menus, buttons and images, but all takes place in the generic Unity skybox.

Repeatable 100% of the time in the latest Cloud Build executable.

**Comment by IxLahiji** [comment]
Issue got fixed in commit aad46e29364758d47ef31997d4ac152f545d1a99

**Comment by snovan** [comment]
room now instantiates at proper vector lcation
