### ISSUE TITLE
Replicated issues on Oculus #1 that cannot be replicated on Oculus #2

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#112]
This issue actually encompasses several issues on the board.  If someone wants to investigate why this is then that would be great.  Possible Fix: Re-calibrate the sensors on Oculus number 1 so we have positions marked at the same distance as Oculus 2.  If this does not work, then look into different programs installed on each machine.

**Comment by mkp003** [comment]
Issue #86

**Comment by mkp003** [comment]
While the sensors do seem to play a role in this, Evan has provided evidence that the issues are due to the workstation.  Switching which workstation runs which oculus has has had no effect on moving the issues to another computer.  This suggests that the workstation is the likely cause of these issues.  This is beyond our ability to fix.

**Comment by EvanSnook** [comment]
we have confirmed that the bug is dependent on the single machine and Is no problem of our programs
