### ISSUE TITLE
Need a way of showing which button is currently selected

### ISSUE THREAD

**Issue by snovan** [IxLahiji/CMPT371Team3#118]
currently it is ridiculously difficult to tell what you are manipulating

**Comment by mkp003** [comment]
Brianne was able to successfully implement "Pushing" butttons.  That is, when the button is selected it will "push" inward, giving the impression that the button is selected.  This is done in the Dashboard script.  On line 216 there is a check to see if any button is selected. If there is none then all buttons are reset.  On line 472 there is a function called setButtonScale which will set the position of each button.  We would like a color change or glow added to this at a later point.

**Comment by nhip** [comment]
Code reviewed.

**Comment by nhip** [comment]
Brianne may be changing the fix.

**Comment by IxLahiji** [comment]
Has been fixed with refactoring

**Comment by IxLahiji** [comment]
Confirmed fixed with acceptance testing
