### ISSUE TITLE
Error thrown when filebrowser attempts to move past the root directory.

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#121]
When in the filebrowser, the user is able to continuously hit back until they reach the root directory.  When they attempt to hit the back button while in the root directory, an error will be thrown saying that no directory exists.  The filebrowser will then be stuck in a state without any files or directories so the user can no longer browse through the system.  We need a better method for checking if we are at a root directory and prevent back form being pressed.

**Comment by mkp003** [comment]
This has now been fixed in the function GetPreviousPath(string path) function in the filebrowser.  It checks if the parent directory is null and just does nothing if it is.

**Comment by EvanSnook** [comment]
fis is implemented and works correctly
