### ISSUE TITLE
Mocking objects for testing gives errors

### ISSUE THREAD

**Issue by KyleS22** [IxLahiji/CMPT371Team3#15]
When using NSubstitute for testing with mock objects, the following error is thrown:
`NUnit System.TypeLoadException : Could not load type 'Castle.Proxies.GameObjectProxy'`

This occurs when running unit tests from the Unity Editor.

**Comment by IxLahiji** [comment]
Has this issue been resolved? I was told a work around was made for this.

**Comment by KyleS22** [comment]
Our work around for this is to create the actual unity game objects, which doesn't really simulate mocking very well.  It helps us write tests for now, but the purpose of mocking is to be able to rely on a 'fake' object to provide unwritten functionality.  At least that's what I understand.  

Basically, we can get around it, but it would be wise to find an actual fix for this.

**Comment by snovan** [comment]
we will no longer be doing automated testing. our solution is to focus on manual testing.
