### ISSUE TITLE
Build Failures, namespaces and testing framework not recognized

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#155]
NOOOOOOOOO!!! The build is currently failing.  The reason is believed to be linked to the Luxsonic machine altering some unknown setting with Nunit.

**Comment by mkp003** [comment]
237: [Unity] Assets/UnityTestTools/IntegrationTestsFramework/TestRunner/Editor/IntegrationTestsRunnerWindow.cs(8,17): error CS0234: The type or namespace name `IntegrationTestRunner' does not exist in the namespace `UnityTest'. Are you missing an assembly reference?
238: [Unity] Assets/UnityTestTools/UnitTesting/Editor/DashboardTests.cs(5,7): error CS0246: The type or namespace name `buttons' could not be found. Are you missing an assembly reference?
239: [Unity] Assets/UnityTestTools/UnitTesting/Editor/SystemTests/SystemTests.cs(7,7): error CS0246: The type or namespace name `buttons' could not be found. Are you missing an assembly reference?
240: [Unity] Assets/UnityTestTools/Assertions/Editor/GroupByExecutionMethodRenderer.cs(8,73): error CS0246: The type or namespace name `CheckMethod' could not be found. Are you missing an assembly reference?
241: [Unity] Assets/UnityTestTools/IntegrationTestsFramework/TestRunner/Editor/IntegrationTestsRunnerWindow.cs(485,32): error CS0246: The type or namespace name `ITestRunnerCallback' could not be found. Are you missing an assembly reference?
242: [Unity] Assets/UnityTestTools/Assertions/Editor/AssertionComponentEditor.cs(89,54): error CS0246: The type or namespace name `AssertionComponent' could not be found. Are you missing an assembly reference?
243: [Unity] Assets/UnityTestTools/Assertions/Editor/AssertionComponentEditor.cs(107,45): error CS0246: The type or namespace name `AssertionComponent' could not be found. Are you missing an assembly reference?
244: [Unity] Assets/UnityTestTools/Assertions/Editor/AssertionComponentEditor.cs(125,40): error CS0246: The type or namespace name `ComparerBase' could not be found. Are you missing an assembly reference?
245: [Unity] Assets/UnityTestTools/Assertions/Editor/AssertionComponentEditor.cs(149,45): error CS0246: The type or namespace name `ComparerBase' could not be found. Are you missing an assembly reference?
246: [Unity] Assets/UnityTestTools/Assertions/Editor/AssertionComponentEditor.cs(166,44): error CS0246: The type or namespace name `ComparerBase' could not be found. Are you missing an assembly reference?
247: [Unity] Assets/UnityTestTools/Assertions/Editor/AssertionComponentEditor.cs(182,44): error CS0246: The type or namespace name `AssertionComponent' could not be found. Are you missing an assembly reference?
248: [Unity] Assets/UnityTestTools/Assertions/Editor/AssertionComponentEditor.cs(212,39): error CS0246: The type or namespace name `AssertionComponent' could not be found. Are you missing an assembly reference?
249: [Unity] Assets/UnityTestTools/Assertions/Editor/AssertionExplorerWindow.cs(16,22): error CS0246: The type or namespace name `AssertionComponent' could not be found. Are you missing an assembly reference?.............. more of the same....

**Comment by mkp003** [comment]
Problem resolved.  Unity updated to version 5.6 and the build automatically changed it's settings to adjust.  Ix has changed it so that it builds for 5.5.1f1 again.

**Comment by EvanSnook** [comment]
unity 5.6 was the issue. this has been resolved
