### ISSUE TITLE
Exception in Test

### ISSUE THREAD

**Issue by IxLahiji** [IxLahiji/CMPT371Team3#21]
**Where**
Line 86 in ImageManager.cs
Error: CDATA[System.NullReferenceException : Object reference not set to an instance of an object]
In the function "CreateDisplay(String)"
Called on line 81 of ImageManagerTests.cs

**Behaviour**
Causes build to fail.

**Repeat-ability**
Is repeatable

**Comment by KyleS22** [comment]
So interesting issue, CreateDisplay does not take a string.... unless this is a typo?

**Comment by IxLahiji** [comment]
That's odd, but that's the error that came up in the builder. Not sure why.

**Comment by mkp003** [comment]
This class does not exist anymore so the issue is no longer a problem.
