### ISSUE TITLE
VR Scene - Double hand grasp-and-release bug 

### ISSUE THREAD

**Issue by oitoku** [IxLahiji/CMPT371Team3#29]
This bug appears when you have grasped an object in a VR scene, and attempt to grab it with your other hand. The object is picked up by the second hand, and transferred, but releasing grip on the first hand causes the object to behave as though it has been put down, freezing it in space.

Reproducible: 100% of the time.
Severity: Major - lots of underlying issues with detecting the release of grip.

**Comment by oitoku** [comment]
Fixed in the graspbugfix branch.

If problem persists, make sure opposite_hand reference is attached to the hands in the Local_Avatar prefab--left hand should have a reference to the right and vice versa.

**Comment by snovan** [comment]
Issue was fixed by adding a condition when the copy is grabbed that only allows you to grab the image your other hand is not currently holding that same copy. Issue had been resolved.
