### ISSUE TITLE
Button Text Renders on top of all objects

### ISSUE THREAD

**Issue by KyleS22** [IxLahiji/CMPT371Team3#30]
The 3d text used for the buttons renders on the top layer.  This means that when a new object such as a copy is created, the text from any buttons beneath it renders on top of the image.

**Comment by mkp003** [comment]
Resolved!  This was fixed using the method found of the site we were initially using:
http://wiki.unity3d.com/index.php?title=3DText

Creating a new shader and applying a Font text material to the 3DText associated with each button resolved the issue.  We had unknowingly fixed this problem earlier, but we discovered that the text was also behind the actual buttons, so it appeared invisible.
