### ISSUE TITLE
Destroy Object Error

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#40]
Occasionally Unity has issue with how we deal with Tray thumbnail deletion where we delete the thumbnails in update to create the new set.  It does not always do this, but sometimes it throws several errors saying that we have to switch to Destroy() instead of DestroyImmediate() (which is the opposite of what the build wants).  I will post the exact error if and when it occurs again.

**Comment by mkp003** [comment]
Kyle and I have finally fixed this issue! The tray will no longer destroy thumbnails and create itself again.

**Comment by herambsawant1** [comment]
Reviewed code

**Comment by snovan** [comment]
Tray's updateTray function was revamped and this error is no longer possible
