### ISSUE TITLE
Scene Merge Conflict with id2_Display

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#41]
There was a merge conflict with this.  Iv'e created a new scene called ID3_Demo for all the VR stuff.  I was going to replicate the id2_display scene and merge it back over but there are currently errors in the Slider branch about missing mesh renders.  Ill need help determining which prefabs you were using and which scripts were adjusted.

**Comment by KyleS22** [comment]
So when we implemented the brightness slider, we created a new object called copy2.  This object replaces the Sprite Renderer with a MeshRenderer.

The fix for this issue is to replace the copy object in the Display object with the copy2 object.
