### ISSUE TITLE
Unauthorised users?

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#42]
I just noticed with the last issue I made that there are 14 users that have access to this? One i know is Professor Osgood and another is the TA? So there should be 12 or 13 in total.  I've attached the two usernames of the people I'm not sure about as assignee's to this issue so that someone can give me info.

**Comment by oitoku** [comment]
In addition to the 11 of us, Professor Osgood and two TAs should have access to the repository. The names check out.

**Comment by mkp003** [comment]
Ok I did not realise there were two TAs. No problem then.

**Comment by IxLahiji** [comment]
Technically there should be 15 users in the repository. The 11 of us, Professor Osgood, the 2 TAs, and Mike from Luxsonic. However, the latter in that list may have accidentally declined the invite to the Repo, or I forgot to add him.
