### ISSUE TITLE
Move list of Copy references from Display.cs to its own class

### ISSUE THREAD

**Issue by oitoku** [IxLahiji/CMPT371Team3#44]
In the March 4 code review, we determined that it would be better to remove the list of Copy object references from the Display, in order to separate concerns of components and to prevent potential bugs when accessing the Copies if the Display is minimized.

Refactor the code to remove the list from Display.cs, and replace with a reference to the list's new location, wherever the new design has placed it.

**Comment by mkp003** [comment]
We will leave this here as it looks like we will need a reference to the copy list for manipulating which is selected.
