### ISSUE TITLE
Investigate and implement Javadoc-style documentation in C#/Unity/Visual Studio

### ISSUE THREAD

**Issue by oitoku** [IxLahiji/CMPT371Team3#45]
As discussed in the March 4 code review, when documenting methods within classes, Visual Studio inserts tags, such as <summary>, around the docstrings.

Investigate this format, and if it has specific tags for things like preconditions, postconditions, throwing exceptions, etc., please incorporate them into the documentation.

**Comment by mkp003** [comment]
Issue investigated.  If you type in threof eache forward slashes above a function it will auto generate tags associated with the function in it's current state.  There are several tags that can be added, the most important (which it auto adds) is summary, params (parameters), and return.  The only thing missing is the description for each which can be added in.  More information can be found here https://msdn.microsoft.com/en-us/library/5ast78ax.aspx
