### ISSUE TITLE
Images cannot be assigned to the display through code

### ISSUE THREAD

**Issue by EvanSnook** [IxLahiji/CMPT371Team3#48]
this can be done through the unity editor no problem, but null reference exceptions are thrown when we try to assign them with code. the add images functionality needs to be more robust rather than how it is currently hard coded

**Comment by mkp003** [comment]
We'll need more detail on the issue in order to address it.

**Comment by mkp003** [comment]
I'm assuming this is related to issue #15? Cannot fix it on developing end, this is an issue with Unity's general dislike of testing tools.

**Comment by snovan** [comment]
This is Unity's issue not ours. see documentation on issues with testing frameworks and the Unity editor
