### ISSUE TITLE
Slider Bar persists if Copy is closed

### ISSUE THREAD

**Issue by IxLahiji** [IxLahiji/CMPT371Team3#51]
If the Slider bar is open when the Copy is closed, the slider bar is still present and there is no way to remove it.
This issue is repeatable.

**Comment by oitoku** [comment]
Is this issue still valid, with the slider bar no longer being incorporated into the UI?

**Comment by mkp003** [comment]
Getting rid of the slider bar has fixed this. No longer a problem.

**Comment by snovan** [comment]
Issue has been resolved as the slider bar no longer exists
