### ISSUE TITLE
Un-handled Case in Next/Previous buttons

### ISSUE THREAD

**Issue by IxLahiji** [IxLahiji/CMPT371Team3#53]
**Area Present:**
**Observed Behaviour:** There is no case to handle if a the Next/Previous buttons are pressed when moving there is no images present. While this case should never come up, it is still important to catch in the event of an error/glitch that might accidentally incite such a situation.
**Repeatable?** N/A

**Comment by mkp003** [comment]
Fixed with an if statement.  Now nothing will happen if this ever occurs.

**Comment by snovan** [comment]
Issue has been fixed, but the user does not receive any useful feedback when the condition happens. please add the appropriate assert, log, or exception

**Comment by KyleS22** [comment]
Fixed this issue by adding an appropriate assert, but this did raise the question of how users will see error message that we want to display to them, I will log this as another issue.

**Comment by nhip** [comment]
Tested in VR

**Comment by herambsawant1** [comment]
Add assertion to make sure buttons only come up when there are 3+ images in the tray
