### ISSUE TITLE
Previously selected copies will continue to change their brightness/contrast/etc.

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#58]
Issue: A copy that has previously been selected and manipulated will continue to be manipulated even after a different copy has been selected.

**Comment by mkp003** [comment]
Repeatable:
1.) select a copy
2.) select a mutator (brightness, contrast, resize...)
3.) manipulate the image
4.) select another image
5.) choose a different mutator
6.) see both copies get changed.

**Comment by mkp003** [comment]
This is now fixed, images will only ever change while they are selected now.  This was fixed by directly removing the selected image from the list of selected copies.

**Comment by herambsawant1** [comment]
Variable name current selection needs to be more specific try currentFilterSelected
