### ISSUE TITLE
3 copies made when selecting them from the tray

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#62]
Issue: Selecting an item from the tray seems to sometimes instantiate three copies.  This issue is generally repeatable.

**Comment by mkp003** [comment]
This is now fixed, a flag has been added to the thumbnails so that images don't do this every frame the user is selecting a thumbnail.

**Comment by snovan** [comment]
Multiple images are still created when the tray is touched. This is likely due to overlapping images, but I will not be closing this issue until it is clear that it has been fixed
