### ISSUE TITLE
Images stuck on hands

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#69]
During user testing, users would occasionally be unable to release an image from their grip.  We believe this is likely due to grabbing two images at once with the same hand.  There are a few ways we can go about fixing this since they stem from the issue of copies instantiating in the same spot.

**Comment by mkp003** [comment]
This may be the result of a previous issue of double grasping the same object with both hands.

**Comment by oitoku** [comment]
This appears to be fixed with the resolution of Issue #29.

**Comment by snovan** [comment]
as previously stated, bug appears to be fixed with the resolution of #29 , no specific regression tests will be implemented, but user testing will be carefully monitored for this bug sould it arise again
