### ISSUE TITLE
Image copies have the same name

### ISSUE THREAD

**Issue by K-Noonan** [IxLahiji/CMPT371Team3#77]
When new copy objects are created in the hierarchy, they all have the same name.  This is generally bad practice.

**Comment by KyleS22** [comment]
Fixed by adding the directory path string in the file browser as the name of the texture passed to the copy, then using that name to name the instantiated copy.

This fix currently resides in the ID5_fixes branch and still needs to be run on the oculus before moving on to review.

**Comment by nhip** [comment]
Tested in VR

**Comment by herambsawant1** [comment]
Reviewed code
