### ISSUE TITLE
Can't see the other side of an image/copy

### ISSUE THREAD

**Issue by K-Noonan** [IxLahiji/CMPT371Team3#84]
This should be made visible

**Comment by KyleS22** [comment]
This is likely a setting on the Sprite Renderer component on the Copy.

**Comment by KyleS22** [comment]
This should be fixable by adding `cull off` to the associated shader.

Will need to try this on the machine to make sure it actually works

**Comment by KyleS22** [comment]
The above mentioned fix does not work

**Comment by snovan** [comment]
issue has been visually resolved
