### ISSUE TITLE
Close does not deactivate

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#87]
Close will not deactivate unless the another manipulator button is pressed.  This is easily repeatable. Any image selected after copy is will be deactivated regardless of it's status.

**Comment by BriKostur** [comment]
issue fixed by adding line of code to copy script: this.currentSelection = CurrentSelection.none in new options(); 
and by setting the current selection to none in dashboard after close has been applied to all the copies in UpdateCopyOptions()

**Comment by herambsawant1** [comment]
Reviewed code
