### ISSUE TITLE
buttons load in different sizes

### ISSUE THREAD

**Issue by BriKostur** [IxLahiji/CMPT371Team3#89]
Buttons will load in different sizes sometimes when you start program with camera looking away from sensors

**Comment by KyleS22** [comment]
This appears to only happen on Oculus 1

**Comment by mkp003** [comment]
See the comments on issue #112 .  Since this is an issue with the workstation we cannot fix it.

**Comment by EvanSnook** [comment]
now that we have a third oculus, we can confirm that this is an issue with the machine and has nothing to do with ourproject
