### ISSUE TITLE
Tray has no limit

### ISSUE THREAD

**Issue by K-Noonan** [IxLahiji/CMPT371Team3#93]
Constantly loading images in on the tray will make the tray go through the floor and the images won't be visible and can't be accessed.

**Comment by KyleS22** [comment]
This issue can be fixed by implementing a scrolling feature on the tray.

**Comment by KyleS22** [comment]
Fixed by implementing scrolling on the tray.  Needs to be run in VR.

**Comment by EvanSnook** [comment]
scrolling has been implemented and fixes the issue
