### ISSUE TITLE
None convex mesh collider with non-kinemetic rigidbody Error.

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#97]
I think @oitoku mentioned a fix to this solution? Consult her on this.

**Comment by KyleS22** [comment]
Would appreciate a better description on this issue.

**Comment by KyleS22** [comment]
this functionality is no longer supported in Unity 5.  If you want to use a non-convex mesh, wither make the rigidbody kinematic, or remove the rigidbody.

**Comment by KyleS22** [comment]
fixed by removing the mesh collider from the copy outline

**Comment by snovan** [comment]
mesh collider was removed and issue no longer occurs
