### ISSUE TITLE
Brightness and contrast go into infinity

### ISSUE THREAD

**Issue by BriKostur** [IxLahiji/CMPT371Team3#98]
Brightness and contrast will go to infinite numbers. should have boundaries.

**Comment by KyleS22** [comment]
This issue is related to either the Image Effects shader or the brightness and contrast functions in the copy class.

**Comment by nhip** [comment]
Tested in VR

**Comment by herambsawant1** [comment]
Add assertions to make sure the brightness and contrast of an image never get below their min value and above their max value
